import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';

const $=s=>document.querySelector(s), scene=new THREE.Scene();
scene.background=new THREE.Color(0x11191a); scene.fog=new THREE.FogExp2(0x192323,.026);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,220);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setSize(innerWidth,innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio,1.65)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=.82; document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0x758b91,0x17160f,1.4)); const moon=new THREE.DirectionalLight(0xc2d6df,2.8); moon.position.set(-20,35,-15); moon.castShadow=true; moon.shadow.mapSize.set(1024,1024); moon.shadow.camera.left=-55;moon.shadow.camera.right=55;moon.shadow.camera.top=55;moon.shadow.camera.bottom=-55; scene.add(moon);
const mat=(c,r=.9)=>new THREE.MeshStandardMaterial({color:c,roughness:r});
const ground=new THREE.Mesh(new THREE.PlaneGeometry(220,220),mat(0x20241e)); ground.rotation.x=-Math.PI/2; ground.receiveShadow=true; scene.add(ground);
// muddy road and graveled shoulders
const road=new THREE.Mesh(new THREE.PlaneGeometry(11,125),mat(0x302c26)); road.rotation.x=-Math.PI/2;road.position.set(0,.012,-22);scene.add(road);
for(let i=0;i<180;i++){const s=Math.random()*.18+.04,o=new THREE.Mesh(new THREE.DodecahedronGeometry(s,0),mat(0x4b4940));o.position.set((Math.random()-.5)*10,.03,-82+Math.random()*122);o.scale.y=.25;scene.add(o)}
function box(w,h,d,c,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);return m}
function house(x,z,rot=0){const g=new THREE.Group();const wall=box(8,5.5,7,0x4a4940,0,2.75,0),roof=new THREE.Mesh(new THREE.ConeGeometry(6.5,3,4),mat(0x211d19));roof.position.y=6.5;roof.rotation.y=Math.PI/4;roof.castShadow=true;g.add(wall,roof); scene.remove(wall);const door=box(1.6,3,.16,0x1c1713,0,1.5,3.55);scene.remove(door);g.add(door);for(const wx of [-2.3,2.3]){const w=box(1.1,1.2,.12,0xb98249,wx,3,3.59);scene.remove(w);g.add(w);const light=new THREE.PointLight(0xd28b42,2.2,9,2);light.position.set(wx,3.1,4);g.add(light)}g.position.set(x,0,z);g.rotation.y=rot;scene.add(g)}
house(-9,-4,.12);house(10,-14,-.16);house(-10,-27,.08);house(10,-40,-.12);house(-11,-52,.1);house(10,-64,-.08);
// chapel silhouette
box(14,10,18,0x3d403b,0,5,-84);box(5,19,5,0x343733,0,9.5,-77);const chapelDoor=box(3.2,5,.3,0x17130f,0,2.5,-74.85);
for(let i=0;i<25;i++){const x=(Math.random()<.5?-1:1)*(15+Math.random()*25),z=-8-Math.random()*90;const trunk=box(.35,3+Math.random()*2,.35,0x29231d,x,2,z);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.6+Math.random(),5,7),mat(0x17231d));crown.position.set(x,5,z);crown.castShadow=true;scene.add(crown)}
const player=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.46,1.15,5,10),mat(0x30383a));body.castShadow=true;body.position.y=1.25;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.34,12,10),mat(0xb9977d));head.position.y=2.25;head.castShadow=true;player.add(head);const gun=box(.12,.12,.75,0x171819,0,0,0);scene.remove(gun);gun.position.set(.45,1.7,-.35);player.add(gun);player.position.set(0,0,11);scene.add(player);
let yaw=0,pitch=-.08,move={x:0,y:0},running=false,aiming=false,hp=100,ammo=12,reserve=36,started=false,keyFound=false,kills=0,lastShot=0;
const enemies=[];function spawnEnemy(x,z){const e=new THREE.Group(),b=new THREE.Mesh(new THREE.CapsuleGeometry(.42,1.0,4,8),mat(0x4b4038)),h=new THREE.Mesh(new THREE.SphereGeometry(.31,10,8),mat(0x87705e));b.position.y=1.15;h.position.y=2.05;b.castShadow=h.castShadow=true;e.add(b,h);e.position.set(x,0,z);e.userData={hp:2,lastHit:0,dead:false};scene.add(e);enemies.push(e)}
[[-4,-15],[4,-25],[-3,-39],[4,-51],[-5,-63],[3,-72]].forEach(p=>spawnEnemy(...p));
const keyMesh=new THREE.Mesh(new THREE.TorusGeometry(.3,.08,8,18),new THREE.MeshStandardMaterial({color:0xd4ad55,metalness:.8,roughness:.2,emissive:0x5a3b0b}));keyMesh.rotation.x=Math.PI/2;keyMesh.position.set(-7,.7,-47);scene.add(keyMesh);const keyLight=new THREE.PointLight(0xd9a94d,2,5);keyLight.position.copy(keyMesh.position);scene.add(keyLight);
function flash(text){const m=$('#message');m.textContent=text;m.style.opacity=1;clearTimeout(flash.t);flash.t=setTimeout(()=>m.style.opacity=0,1700)}
function updateHUD(){$('#hp').textContent=Math.max(0,Math.round(hp));$('#ammo').textContent=ammo;$('#reserve').textContent=reserve}
function shoot(){const now=performance.now();if(!started||now-lastShot<280)return;if(!ammo){flash(reserve?'Tap FIRE to reload':'Out of ammunition');if(reserve){const n=Math.min(12,reserve);ammo=n;reserve-=n;updateHUD()}return}lastShot=now;ammo--;updateHUD();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(aiming?.12:0,0),camera);const hits=ray.intersectObjects(enemies.filter(e=>!e.userData.dead),true);if(hits.length){let e=hits[0].object;while(e.parent&&!enemies.includes(e))e=e.parent;if(enemies.includes(e)){e.userData.hp--;e.userData.lastHit=now;e.children.forEach(c=>c.material.color.setHex(0x8e2622));setTimeout(()=>{if(!e.userData.dead)e.children.forEach((c,i)=>c.material.color.setHex(i?0x87705e:0x4b4038))},110);if(e.userData.hp<=0){e.userData.dead=true;kills++;e.rotation.z=Math.PI/2;e.position.y=.5;flash('Threat neutralized')}}}renderer.domElement.animate([{filter:'brightness(1.8)'},{filter:'brightness(1)'}],{duration:70})}
function bindHold(el,on,off){el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);on()});el.addEventListener('pointerup',off);el.addEventListener('pointercancel',off)}bindHold($('#aim'),()=>aiming=true,()=>aiming=false);bindHold($('#run'),()=>running=true,()=>running=false);bindHold($('#fire'),shoot,()=>{});
const stick=$('#stick'),knob=$('.knob');stick.addEventListener('pointerdown',e=>stick.setPointerCapture(e.pointerId));stick.addEventListener('pointermove',e=>{if(!stick.hasPointerCapture(e.pointerId))return;const r=stick.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),l=Math.min(38,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);move.x=Math.cos(a)*l/38;move.y=Math.sin(a)*l/38;knob.style.transform=`translate(${move.x*38}px,${move.y*38}px)`});function zero(){move.x=move.y=0;knob.style.transform='translate(0,0)'}stick.addEventListener('pointerup',zero);stick.addEventListener('pointercancel',zero);
let lookId=null,lx=0,ly=0;renderer.domElement.addEventListener('pointerdown',e=>{if(e.clientX<innerWidth*.35)return;lookId=e.pointerId;lx=e.clientX;ly=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(e.pointerId!==lookId)return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;yaw-=dx*.006;pitch=THREE.MathUtils.clamp(pitch-dy*.004,-.42,.32)});renderer.domElement.addEventListener('pointerup',e=>{if(e.pointerId===lookId)lookId=null});
$('.startbtn').onclick=async()=>{started=true;$('#start').style.display='none';try{await document.documentElement.requestFullscreen?.()}catch{}flash('Find the chapel key');};
const clock=new THREE.Clock(),v=new THREE.Vector3();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.035),now=performance.now();if(started&&hp>0){player.rotation.y=yaw;const forward=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));v.copy(forward).multiplyScalar(-move.y).addScaledVector(right,move.x);if(v.lengthSq())v.normalize().multiplyScalar((running?6.2:3.6)*dt);player.position.add(v);player.position.x=THREE.MathUtils.clamp(player.position.x,-6,6);player.position.z=THREE.MathUtils.clamp(player.position.z,-72,13);const camDist=aiming?3.2:5.2,side=aiming?1.1:1.5;const target=player.position.clone().add(new THREE.Vector3(0,1.65,0));const offset=new THREE.Vector3(Math.sin(yaw)*camDist+Math.cos(yaw)*side,2.25+pitch*3,Math.cos(yaw)*camDist-Math.sin(yaw)*side);camera.position.lerp(target.clone().add(offset),1-Math.pow(.002,dt));camera.lookAt(target.clone().add(forward.multiplyScalar(-8)).add(new THREE.Vector3(0,pitch*8,0)));$('#crosshair').style.opacity=aiming?.95:.2;
      if(!keyFound&&player.position.distanceTo(keyMesh.position)<1.8){keyFound=true;keyMesh.visible=keyLight.visible=false;$('#obj').textContent='Reach the chapel';flash('Chapel key acquired')}
      if(keyFound&&player.position.z<-70){$('#obj').textContent='Escape complete';flash(kills>=3?'DEMO COMPLETE — You survived':'DEMO COMPLETE — Barely');started=false}
      for(const e of enemies){if(e.userData.dead)continue;const d=e.position.distanceTo(player.position);if(d<18){const dir=player.position.clone().sub(e.position).setY(0).normalize();e.position.addScaledVector(dir,dt*(d<2?0:1.35));e.lookAt(player.position.x,e.position.y,player.position.z);if(d<1.55&&now-e.userData.lastHit>950){e.userData.lastHit=now;hp-=9;updateHUD();$('#damage').style.opacity=.55;setTimeout(()=>$('#damage').style.opacity=0,120);if(hp<=0){flash('YOU DIED — Reload the page');started=false}}}}
    }renderer.render(scene,camera)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});updateHUD();
